### PR TITLE
Add support for an externally generated template database to EfClassicLocalDb

### PR DESCRIPTION
**Pull request by benrhughes**
This change allows localdb to manage a more complex database, for example one with stored procs, reference data etc.

### CODE REVIEW

**Comment by benrhughes** [comment]
Sorry - I only ran the EfClassic test suit; didn't realise that there were other relevant tests. I'll look into the failure and push a fix.

**Comment by SimonCropp** [comment]
awesome idea. i will review when u have the tests passing

**Comment by benrhughes** [comment]
Thanks. Not sure if you saw my comment on the PR, but the tests all pass for me locally (on multiple runs). I'm not sure how to chase down why they're failing in the CI run.










---- On Sun, 26 Apr 2020 19:46:14 +1000 Simon Cropp <notifications@github.com> wrote ----





awesome idea. i will review when u have the tests passing

**Comment by SimonCropp** [comment]
in that case let me have a look.

**Comment by SimonCropp** [comment]
can u add a new test to verify this feature

**Comment by SimonCropp** [comment]
bump

**Comment by benrhughes** [comment]
:) I'll get to the tests in the next couple of days - we have a prod release this week so that's taken all my focus. 






---- On Thu, 30 Apr 2020 20:06:11 +1000 Simon Cropp <mailto:notifications@github.com> wrote ----




bump

**Comment by SimonCropp** [comment]
no worries. I think your PR is good. just want the tests to ensure it continues to work in the future. hope your prod release goes well

**Comment by benrhughes** [comment]
I'm in Aranda






---- On Thu, 30 Apr 2020 20:54:53 +1000 notifications@github.com wrote ----



BTW where r u in canberra? I am in Watson

**Comment by benrhughes** [comment]
Hi @SimonCropp, 
I've added a test case and everything seems to be passing. Sorry for the delay; it has been one of those weeks :)

Cheers,

Ben

**Comment by SimonCropp** [comment]
LGTM. can u add a bit of doco to here https://github.com/SimonCropp/LocalDb/blob/master/readme.source.md

then i will merge and release

**Comment by benrhughes** [comment]
Done. I think I got the markdown/snippet thing right, let me know if I messed it up.

**Pull request merged**
